### ISSUE TITLE
Source of Shapefiles

### ISSUE THREAD

**Issue by suzairjunaid** [cerp-analytics/pbs2017#1]
The shapefiles seem to be from [this](https://data.humdata.org/dataset/pakistan-union-council-boundaries-along-with-other-admin-boundaries-dataset) source. It good if @ahwazakhtar can check if this is indeed the correct source.

I wanted to flag two things about the shapefiles:

1. The linked database was probably created using [OCHA's admin boundaries database](https://data.humdata.org/dataset/pakistan-administrative-level-0-1-2-and-3-boundary-polygons-lines-and-central-places) for Pakistan, among other sources. I wanted to highlight that there are some differences between the boundaries in these two sources. The differences are more apparent at the tehsil / adm3 level. We would need investigate which of the two are more accurate / appropriate for use.

2. The constituencies shapefiles in the repository probably correspond to the delineation of constituency boundaries done before the 2013. There is nothing wrong in using these. Just wanted to flag this in case users think the boundaries reflect the delimitation from 2017-18.

**Comment by ahwazakhtar** [comment]
Yes you are correct regarding the shapefile source and the caveats that apply regarding the accuracy. I am updating the documentation to reflect this.

Thanks @suzairjunaid !
